### ISSUE TITLE
Error that i dont understand

### ISSUE THREAD

**Issue by LeonGamerHD** [pypy-vrc/VRCX#151]
code = CantOpen (14), message = System.Data.SQLiteException (0x800007FF): unable to open database file
at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
at System.Data.SQLite.Connection.Open()
at VRCX.Program.Run() in
C:\Work\VS2019\VRC\Program.cs:row 40.
at VRCX.Program.Run() in
C:\Work\VS2019\VRC\Program.cs:row 25.

**Comment by LeonGamerHD** [comment]
the problem was that I had VRCX in my programs folder and didn't start it as administrator
